# Generated by Django 2.0.6 on 2019-09-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('roleId', models.CharField(default='', max_length=200)),
                ('UserFullName', models.CharField(default='', max_length=200)),
                ('UserEmail', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('UserPassword', models.CharField(default='', max_length=200)),
                ('UserMobile', models.BigIntegerField()),
                ('UserImage', models.CharField(default='', max_length=200)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
